### ISSUE TITLE
Support Schema Aliasing in `.configu` Configuration File

### ISSUE THREAD

**Issue by rannn505** [configu/configu#360]
### Suggestion

Introduce a `schemas` section to the `.configu` configuration file to allow aliasing of schema file paths. This feature enables users to refer to schemas by simple, memorable names rather than specifying full file paths in command-line operations. The `schemas` dictionary maps custom alias names to relative or absolute paths of `ConfigSchema` files.

**Example Configuration:**
```yaml
stores:
  Configu:
    type: configu
    configuration:
      credentials:
        org: configu
  # Other store configurations...

schemas:
  common: 'packages/common/common.cfgu.json'
  infra: 'packages/infra/infra.cfgu.json'
  dal: 'packages/dal/dal.cfgu.json'
  api: 'packages/api/api.cfgu.json'

scripts:
  dev:api: |
    configu eval --schema 'common' \
      | configu eval --schema 'infra' \
      | configu eval --schema 'dal' \
      | configu eval --schema 'api' \
      | configu export --format 'Dotenv' > packages/api/.env
  # Other script configurations...
```
In this setup, schema aliases such as `common`, `infra`, `dal`, `api` are defined under `schemas`, pointing to their respective JSON schema files. This allows the user to utilize these aliases in CLI commands for more concise and readable scripts.

### Motivation

Schema aliasing simplifies the usage of frequently referenced schemas across various scripts and commands within a project. By providing a centralized place for schema path definitions, this feature reduces redundancy, minimizes potential for errors in path specification, and enhances readability and maintainability of configuration-related scripts.

### Context

The `.configu` file supports both YAML and JSON formats, offering flexibility in how configurations are structured. This proposal extends its utility by leveraging it for schema path aliasing, encouraging a more organized and efficient approach to managing configuration schema references within Configu projects.

This enhancement builds on existing functionalities of the `.configu` configuration file, aligning with the goal of making Configu more user-friendly and adaptable to diverse project structures.
