### ISSUE TITLE
Enable remote `ConfigSchema`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#439]
### Suggestion

Enable the use of remote `ConfigSchema` by allowing the schema flag for the Configu interface both on the CLI (`--schema` flag) and in the `.configu` file (`schemas` keyword) to be a URL. Configu will fetch the schema from the URL and use it the same as with a local file.

### Motivation

Enabling remote `ConfigSchema` enhances flexibility and scalability by allowing schemas to be hosted remotely.
This feature will aid in remote execution of the CLI, such as in CI/CD pipelines, where schemas of common keys may be hosted in another repository.
it will align Configu interfaces with popular dev tools like `kubectl` and `helm` which have this kind of capability.

### Context

In the GitOps approach advocated by Configu, users are encouraged to store schemas next to the code that requires them as configuration. This practice ensures that configurations are versioned alongside the code, promoting consistency and traceability. However, there are scenarios where remote execution of the CLI is necessary, such as in CI/CD pipelines, and schemas might be hosted in a different repository. This feature allows Configu to fetch schemas from specified URLs, ensuring that remote execution environments have access to the necessary configurations.

For schemas that are private and cannot be fetched with a simple GET request, users will need to be authorized to perform such operations. This might involve setting tokens for the service, such as Personal Access Tokens (PAT) for private GitHub repositories.

Example of a Github Action that checkouts configSchemas from another repository to pass them to the cli

```yaml
steps:
   ....

	- name: Checkout
	  uses: actions/checkout@v4
	  with:
	    sparse-checkout: |
	      GlobalConfigVariables.cfgu.json
	      Charts/${{ env.CHART }}/values.tmpl.${{ env.DEPLOYMENT_ENVIRONMENT }}.yaml
	    sparse-checkout-cone-mode: false
	
	- name: List files
	  run: |
	    ls -la
	    ls -ltrh Charts/${{ env.CHART }}/
	...
```
