### ISSUE TITLE
ini-file store seems to be missing

### ISSUE THREAD

**Issue by LongBeachHXC** [configu/configu#689]
### Current Behavior

I just upgraded my Configu CLI to the 1.0 release. I'm having issues using the `ini-file` and `toml-file` stores. I also tested the `json-file` store and did NOT receive any errors.

```
configu upsert --verbose --store localToml --set test --schema test.cfgu.yaml --assign "TEST_KEY=false"

 ERROR  store toml-file not found                                                                                                                                                                                                                                                                      5:31:45 AM

    at ConfiguFile.registerStore (dist/configu.cjs:1571:2369)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConfiguFile.constructStore (dist/configu.cjs:1571:2647)
    at async ConfiguInterface.getStoreInstance (dist/configu.cjs:1575:609)
    at async a2.execute (dist/configu.cjs:1575:4630)
    at async a2.validateAndExecute (dist/configu.cjs:1374:748)
    at async e.run (dist/configu.cjs:1388:2434)
    at async run (dist/configu.cjs:1588:319)
```
```
configu upsert --store localIni --set test --schema test.cfgu.yaml --assign "TEST_KEY=false"

 ERROR  store ini-file not found                                                                                                                                                                                                                                                                       5:26:58 AM

    at ConfiguFile.registerStore (dist/configu.cjs:1571:2369)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConfiguFile.constructStore (dist/configu.cjs:1571:2647)
    at async ConfiguInterface.getStoreInstance (dist/configu.cjs:1575:609)
    at async a2.execute (dist/configu.cjs:1575:4630)
    at async a2.validateAndExecute (dist/configu.cjs:1374:748)
    at async e.run (dist/configu.cjs:1388:2434)
    at async run (dist/configu.cjs:1588:319)


```
```
configu upsert --verbose --store localJson --set test --schema test.cfgu.yaml --assign "TEST_KEY=false"
✔ Configs upserted successfully  
```
```
configu --version
1.0.0

# .configu
stores:
  localJson:
    type: json-file
    configuration:
      path: config-store.json
  localIni:
    type: ini-file
    configuration:
      path: config-store.ini
  localToml:
    type: toml-file
    configuration:
      path: config-store.toml
```
```
# config.cfgu.yaml
---
TEST_KEY:
  description: This is just an example
  type: String
...
```

### Expected Behavior

I would expect the ini and toml file stores to operate like the json-file store.

### To Reproduce

_No response_

### Context

_No response_

**Comment by rannn505** [comment]
From Discord:
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/68d41bff-fe00-424f-b561-47835e194160" />

**Comment by rannn505** [comment]
As a temporary workaround you can change your `.configu` to this:

YAML:
```
$schema: https://files.configu.com/schema/.configu.json
stores:
  localJson:
    type: json-file
    configuration:
      path: config-store.json
  localIni:
    type: ini-file@next
    configuration:
      path: config-store.ini
  localToml:
    type: toml-file@next
    configuration:
      path: config-store.toml
```
