### ISSUE TITLE
Export configmap should convert numerical and boolean values to string first

### ISSUE THREAD

**Issue by dipsywong98** [configu/configu#718]
### Suggestion

Hi team, thanks for the nice project and we are trying to use configu to manage our configs in k8s deployments! However, we start seeing some issues when trying to adopt configu and this is a major one

Kubenetes config maps expect all values to be string, but configu has some type conversion to make numerical string into number and booleanic string to Boolean, but as the formatter is just putting the values as it is, so it will output config map with non string value. I could not find a way to stop this type convertion.

For example with this `example.cfgu.yaml`

```yaml
$schema: 'https://files.configu.com/schema/.cfgu.json'
keys:
  NUM:
    default: 123
  BOOL:
    default: true
  NUM_S:
    default: '123'
  BOOL_S:
    default: 'true'
  STRING:
    default: 'some-string'
  STRING_SPACE:
    default: 'some string'
```

and run `configu eval | configu export --format config-map`, I will expect it to give

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2025-03-06T15:35:24.271Z
data:
  NUM: '123'
  BOOL: 'true'
  NUM_S: '123'
  BOOL_S: 'true'
  STRING: some-string
  STRING_SPACE: some string
```

but actually, it is

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2025-03-06T15:35:24.271Z
data:
  NUM: 123
  BOOL: true
  NUM_S: 123
  BOOL_S: true
  STRING: some-string
  STRING_SPACE: some string
```

I have also try some work around - export to dotenv and use kubectl to create configmap from dotenv file, but this does not work. Reusing the same example, `configu eval | configu export --format dotenv > my.env` will give

```dotenv
NUM=123
BOOL=true
NUM_S=123
BOOL_S=true
STRING=some-string
STRING_SPACE="some string"
```

Then convert to config map using `kubectl create configmap my-config --from-env-file=my.env --dry-run -o yaml`

```yaml
apiVersion: v1
data:
  BOOL: "true"
  BOOL_S: "true"
  NUM: "123"
  NUM_S: "123"
  STRING: some-string
  STRING_SPACE: '"some string"'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: my-config
```

Looks like it can solve the above two points, have name and all values are string, but the value of STRING_SPACE now got extra quotes. It is due to k8s considers the quote in env file as part of the literal, and maintainer expects the env to have the quotes removed at the first place instead of assuming k8s will remove it. (Maybe can also consider removing the extra quotes in dotenv export?)

https://github.com/kubernetes-sigs/kustomize/issues/4525#issuecomment-1223288283

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files

So the only "working" workaround for putting bool/number value to configmap is putting extra quotes

```yaml
$schema: 'https://files.configu.com/schema/.cfgu.json'
keys:
  NUM_SS:
    default: '"123"'
  BOOL_SS:
    default: '"true"'
```

can give 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2025-03-06T15:50:18.155Z
data:
  NUM_SS: "123"
  BOOL_SS: "true"
```

However this workaround will leads to extra quote when outputting in other format, which I dont think is a proper way to solve the problem. So to really make the configmap export work nicely, I think configu need to convert the values to string before putting them into the yaml file, as no one would expect number and boolean value in a config map.

I have a quick implementation for this, will submit PR shortly.

**Comment by dipsywong98** [comment]
Update: my colleague is so strong that he find that export to ini format will not generate the extra quote.

So for now anyone facing the same problem can use the below script (at least working at the moment of writing)

```bash
configu eval | configu export --format ini > my.env
kubectl create configmap my-config --from-env-file=my.env --dry-run -o yaml
```

**Comment by rannn505** [comment]
Thanks for bringing this up! I totally agree we should standardize the `config-map` formatter, and we'll address this ASAP. I reviewed your PR (#719)—thanks for submitting! While it provides a quick fix, I'd suggest involving the official Kubernetes SDK to ensure full alignment with the Kubernetes specification.

Meanwhile, as a workaround, you can leverage Configu’s built-in `export --template` feature to control exactly how your ConfigMaps are formatted.

Here's a quick example:

**`myconfigmap.tmpl.yaml`**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.configs.ConfigMapName.value }}
data:
{{ _.chain($.configs).map(({ key, value }) => `  ${key}: "${value}"`).join('\n').value() }}
```
_(Inspired by the [[official Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/configmap/#using-configmaps-as-environment-variables)](https://kubernetes.io/docs/concepts/configuration/configmap/#using-configmaps-as-environment-variables))_

**`myschema.cfgu.yaml`**
```yaml
$schema: 'https://files.configu.com/schema/.cfgu.json'
keys:
  ConfigMapName:
    default: 'myconfigmap'
  NUM:
    default: '123'
```

Then generate the ConfigMap YAML:
```bash
configu eval | configu export --template './myconfigmap.tmpl.yaml' > ./myconfigmap.yaml
```

This gives you immediate control over formatting while we properly fix the built-in formatter.
