### ISSUE TITLE
Option to supply name when exporting k8s config map

### ISSUE THREAD

**Issue by dipsywong98** [configu/configu#720]
### Suggestion

I am using configu to manage configurations and export the configs to a k8s config map, however I could not find a way to supply a name to the config map definition as required by k8s.

For example I have a `fruit.cfgu.yaml`

```yaml
$schema: 'https://files.configu.com/schema/.cfgu.json'
keys:
  FRUIT:
    default: banana
```

And I run `configu eval | configu export --format config-map`, it gives

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2025-03-07T12:26:56.567Z
data:
  FRUIT: banana
```

But the response is missing `metadata.name` to work so I am looking for a direct way to properly supply the config map name, so it can output.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fruit-config
  creationTimestamp: 2025-03-07T12:26:56.567Z
data:
  FRUIT: banana
```

I took a further look into how the configmap export is implemented, there is `name: options?.name?.toLowerCase()` in [the `KubernetesConfigMapFormatter` ](https://github.com/configu/configu/blob/1cd9d85ac252c68232aff7d6b4757bdbf3c0b0d5/packages/formatters/src/YAML.ts#L22) but looks like the value of `options` is always to be `{}` as I see in [reduceConfigs](https://github.com/configu/configu/blob/1cd9d85ac252c68232aff7d6b4757bdbf3c0b0d5/packages/cli/src/commands/export.ts#L188), so I suspect there is no way to supply a value to `options` at the moment, not sure if I read the code correctly. And I think adding this option will change the cli and quite a bit of architecture, so I hold back from directly submitting a PR, but I am happy to contribute.

For anyone facing the same issue, I will suggest doing the following, as there is another issue causing k8s config map export is not working out of the box - https://github.com/configu/configu/issues/718

```bash
configu eval | configu export --format ini > fruit.env
kubectl create configmap fruit-config --from-env-file=fruit.env --dry-run -o yaml > fruit-config.yaml
```
